Models/EventDecorLayOuts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ChurchSystem.Models
{
    public class EventDecorLayOuts
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Layoutid { get; set; }
        public string layoutName { get; set; }
        public string layoutImageUrl { get; set; }

    }
}

Controllers/EventDecorLayOutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChurchSystem.Migrations;
using ChurchSystem.Models;

namespace ChurchSystem.Controllers
{
    public class EventDecorLayOutsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: EventDecorLayOuts
        public ActionResult Index()
        {
            return View(db.EventDecorLayOuts.ToList());
        }

        // GET: EventDecorLayOuts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventDecorLayOuts eventDecorLayOuts = db.EventDecorLayOuts.Find(id);
            if (eventDecorLayOuts == null)
            {
                return HttpNotFound();
            }
            return View(eventDecorLayOuts);
        }

        // GET: EventDecorLayOuts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventDecorLayOuts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Layoutid,layoutName,layoutImageUrl")] EventDecorLayOuts eventDecorLayOuts)
        {
            if (ModelState.IsValid)
            {
                //cici-iqiniso
                HttpPostedFileBase file = Request.Files["ImageFile"];
                //Simmy
                if (file != null && file.ContentLength > 0)
                {
                    // Read the file content into a byte array
                    byte[] fileBytes;
                    using (BinaryReader reader = new BinaryReader(file.InputStream))
                    {
                        fileBytes = reader.ReadBytes(file.ContentLength);
                    }

                    // Convert the byte array to a Base64 string
                    string base64String = Convert.ToBase64String(fileBytes);

                    // Set the ImageData property to the Base64 string
                    eventDecorLayOuts.layoutImageUrl = base64String;
                }

                db.EventDecorLayOuts.Add(eventDecorLayOuts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eventDecorLayOuts);
        }

        // GET: EventDecorLayOuts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventDecorLayOuts eventDecorLayOuts = db.EventDecorLayOuts.Find(id);
            if (eventDecorLayOuts == null)
            {
                return HttpNotFound();
            }
            return View(eventDecorLayOuts);
        }

        // POST: EventDecorLayOuts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Layoutid,layoutName,layoutImageUrl")] EventDecorLayOuts eventDecorLayOuts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventDecorLayOuts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventDecorLayOuts);
        }

        // GET: EventDecorLayOuts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventDecorLayOuts eventDecorLayOuts = db.EventDecorLayOuts.Find(id);
            if (eventDecorLayOuts == null)
            {
                return HttpNotFound();
            }
            return View(eventDecorLayOuts);
        }

        // POST: EventDecorLayOuts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventDecorLayOuts eventDecorLayOuts = db.EventDecorLayOuts.Find(id);
            db.EventDecorLayOuts.Remove(eventDecorLayOuts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/EventDecorLayOuts/Create.cshtml
@model ChurchSystem.Models.EventDecorLayOuts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "EventDecorLayOuts", FormMethod.Post, new { enctype = "multipart/form-data", @class = "vehicle-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EventDecorLayOuts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.layoutName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.layoutName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.layoutName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <input type="file" name="ImageFile" id="ImageFile" />
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";

}

<script>
    @section scripts{


    }
</script>

Views/EventDecorLayOuts/Delete.cshtml
@model ChurchSystem.Models.EventDecorLayOuts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventDecorLayOuts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.layoutName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.layoutName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.layoutImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.layoutImageUrl)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";

}

<script>
    @section scripts{


    }
</script>

Views/EventDecorLayOuts/Details.cshtml
@model ChurchSystem.Models.EventDecorLayOuts

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>EventDecorLayOuts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.layoutName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.layoutName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.layoutImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.layoutImageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Layoutid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";

}

<script>
    @section scripts{


    }
</script>

Views/EventDecorLayOuts/Edit.cshtml
@model ChurchSystem.Models.EventDecorLayOuts

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EventDecorLayOuts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Layoutid)

        <div class="form-group">
            @Html.LabelFor(model => model.layoutName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.layoutName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.layoutName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.layoutImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.layoutImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.layoutImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";

}

<script>
    @section scripts{


    }
</script>

Views/EventDecorLayOuts/Index.cshtml
@model IEnumerable<ChurchSystem.Models.EventDecorLayOuts>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<!-------
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.layoutName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.layoutImageUrl)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.layoutName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.layoutImageUrl)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Layoutid }) |
                @Html.ActionLink("Details", "Details", new { id = item.Layoutid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Layoutid })
            </td>
        </tr>
    }

</table>
    -->
<center>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card">

                    <img src="data:image/png;base64,@(item.layoutImageUrl)" alt="Church Leader Image" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">@item.layoutName</h5>
                        <p class="card-text">


                        </p>
                    </div>

                </div>
            </div>
        }
    </div>
</center>



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/dLayout.cshtml";

}

<script>
    @section scripts{


    }
</script>