Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Permissions;
using System.Web;

namespace ChurchSystem.Models
{
    public class Student
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int StudentId { get; set; }
        public int UserId { get; set; }
 
    }
}

Controllers/QuizzesController.cs
using ChurchSystem.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChurchSystem.Controllers
{
    public class QuizzesController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Quizzes
        public ActionResult Index()
        {
            return View(db.Quizzes.ToList());
        }

        public ActionResult students()
        {
            var students = db.StudentQuizResult.Select(a => a.user).Distinct().ToList();

            ViewBag.Students = students;

            return View();
        }


        public ActionResult userReport(string username)
        {

            var attempts = db.StudentQuizResult.Where(a => a.user == username).ToList();

            List<StudentQuizResult> allattempts = db.StudentQuizResult.Where(c => c.user == username).ToList();
            int allPassed = db.StudentQuizResult.Where(b => b.Passed == "true").Count();
            int completed = db.StudentQuizResult.Where(b => b.Passed == "true").Select(a=>a.QuizId).FirstOrDefault();
            int quizcourse = db.Quizzes.Where(a => a.QuizID == completed).Select(a => a.CourseId).FirstOrDefault();
            string course = db.Courses.Where(b => b.CourseId == quizcourse).Select(a => a.CourseName).FirstOrDefault();
            //int allQuizzes = db.Quizzes.Where(a => a.CourseId == id).Count();
            int passedattempts = 0;






            ViewBag.comp = course;
            foreach (var item in allattempts.Where(m => m.Passed == "true"))
            {
                passedattempts++;
            }

           /* if (passedattempts >= allQuizzes)
            {
                ViewBag.comp = true;
            }*/



            return View(attempts);         
        }

        public ActionResult Create(int CourseId)
        {
            ViewBag.CID = CourseId;
            return View();
        }

        // POST: Quizzes/Create
        // Controllers/QuizzesController.cs

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Quiz quiz)
        {          
            if (ModelState.IsValid)
            {
                quiz.CreatedAt = DateTime.Now;

                db.Quizzes.Add(quiz);
                db.SaveChanges();

                // Redirect to the AddQuestions method with the newly created quiz ID
                return RedirectToAction("AddQuestions", new { QuizId = quiz.QuizID });
            }
            return View(quiz);
        }

        public ActionResult AddQuestions(int QuizId)
        {
            var quiz = db.Quizzes.Find(QuizId);
            if (quiz == null)
            {
                return HttpNotFound(); // Return a 404 error if the quiz does not exist
            }
            return View(new Question { QuizId = QuizId }); // Pass the quiz ID to the view
        }

        // Controllers/QuizzesController.cs

        // Controllers/QuizzesController.cs

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddQuestions(Question question)
        {
            if (ModelState.IsValid)
            {

                // Check if the QuizId is valid
                var quiz = db.Quizzes.Find(question.QuizId);
                if (quiz == null)
                {
                    ModelState.AddModelError("", "The specified quiz does not exist.");
                    return View(question); // Return the same view if the quiz does not exist
                }

                // Now we can safely add the question
                db.Question.Add(question);
                db.SaveChanges();
                return RedirectToAction("Finish", new { id = question.QuizId }); // Redirect after successful addition
            }
            return View(question); // Return the same view if model state is invalid
        }

        public ActionResult Finish(int id)
        {
            var questions = db.Question.Where(a => a.QuizId == id).ToList();
            var courseid = db.Quizzes.Where(a => a.QuizID == id).Select(a=> a.CourseId).FirstOrDefault();

            ViewBag.Id = id;
            ViewBag.QS = questions;
            ViewBag.CID = courseid;
            return View();
        }

        public ActionResult DeleteConfirmed(int id)
        {
            Question itemDonations = db.Question.Find(id);
            int Qid = itemDonations.QuizId;
            db.Question.Remove(itemDonations);
            db.SaveChanges();
            return RedirectToAction("Finish", new { id = Qid});
        }

        public ActionResult QDeleteConfirmed(int id)
        {
            Quiz itemDonations = db.Quizzes.Find(id);
            int Qid = itemDonations.CourseId;
            db.Quizzes.Remove(itemDonations);
            db.SaveChanges();
            return RedirectToAction("quizIndex", new { id = Qid, successMessage = "Quiz Removed" });
        }



        // GET: Quizzes/Take/5
        [Authorize]
        public ActionResult Take(int id)
        {
            var quiz = db.Quizzes.Include("Questions").FirstOrDefault(q => q.QuizID == id);
            if (quiz == null)
            {
                return HttpNotFound();
            }

            // Shuffle answers for each question
            foreach (var question in quiz.Questions)
            {
                var answers = new List<string> { question.CorrectAnswer, question.Answer, question.Answer2 };
                question.ShuffledAnswers = answers.OrderBy(a => Guid.NewGuid()).ToList(); // Shuffling the answers
            }

            return View(quiz);
        }

        // POST: Quizzes/Take/5
        [HttpPost]
        public ActionResult Take(int id, FormCollection form)
        {
            var quiz = db.Quizzes.Include("Questions").FirstOrDefault(q => q.QuizID == id);
            if (quiz == null)
            {
                return HttpNotFound();
            }

            var questionsList = quiz.Questions.ToList();
            int score = 0;

            var studentId = User.Identity.GetUserId(); // Get the current user's ID
            var studentResult = new StudentQuizResult
            {
                StudentId = studentId,
                QuizId = quiz.QuizID,
                Score = score,
                user = User.Identity.GetUserName(),
                Passed = "true"
            };

            db.StudentQuizResult.Add(studentResult);
            db.SaveChanges(); // Ensure studentResult is saved to get the StudentQuizResultId

            for (int i = 0; i < questionsList.Count; i++)
            {
                var questionId = questionsList[i].Id.ToString();
                var submittedAnswer = form["answers_" + questionId];

                bool isCorrect = (submittedAnswer == questionsList[i].CorrectAnswer);
                if (isCorrect)
                {
                    score++;
                }

                var attempt = new QuizAttempt()
                {
                    StudentQuizResultId = studentResult.StudentQuizResultId,
                    QuestionId = questionsList[i].Id,
                    SubmittedAnswer = submittedAnswer,
                    CorrectAnswer = questionsList[i].CorrectAnswer,
                    IsCorrect = isCorrect,
                    user = User.Identity.GetUserName()
                };

                db.QuizAttempt.Add(attempt);
            }

            studentResult.Score = score;

            db.SaveChanges();

            return RedirectToAction("AttemptReview", new { id = studentResult.StudentQuizResultId });
        }

        public ActionResult Details(int id)
        {
            var title = db.Quizzes.Where(a=>a.QuizID==id).Select(a=>a.Title).FirstOrDefault();  
            var Date = db.Quizzes.Where(a => a.QuizID == id).Select(a => a.CreatedAt).FirstOrDefault();
            var qCount = db.Question.Where(a=>a.QuizId == id).Count();
            
            ViewBag.ID = id;
            ViewBag.T = title;
            ViewBag.QC = qCount;
            ViewBag.Date = Date;

            return View();
        }

        public ActionResult ViewResults(int id)
        {
            var attempts = db.StudentQuizResult.Where(a=> a.Quiz.CourseId == id).ToList();

            return View(attempts);
        }

        public ActionResult quizIndex(int id)
        {
            var qz = db.Quizzes.Where(a => a.CourseId == id).ToList();
            ViewBag.ID = id;

            ViewBag.qz = qz;
            return View();
        }

        public ActionResult AdminAttemptReview(int id)
        {
            var quizattempt = db.QuizAttempt.Where(a => a.StudentQuizResultId == id).ToList();
            var user = db.QuizAttempt.Where(a => a.StudentQuizResultId == id).Select(a=>a.user).FirstOrDefault();
            var courseid = db.QuizAttempt.Where(a => a.StudentQuizResultId == id).Select(a=>a.Question.Quiz.CourseId).FirstOrDefault();

            ViewBag.CID = courseid;
            ViewBag.QA = quizattempt;
            ViewBag.user = user;
            return View();
        }


        // GET: Quizzes/Review/5
        public ActionResult Review(int id)
        {
            var result = db.StudentQuizResult.Include("Quiz").FirstOrDefault(r => r.StudentQuizResultId == id);
            return View(result);
        }

        public ActionResult AttemptReview(int id)
        {
            var quizattempt = db.QuizAttempt.Where(a => a.StudentQuizResultId == id).ToList();
            var CID = db.StudentQuizResult.Include("Quiz").Where(a => a.StudentQuizResultId == id).Select(a=>a.Quiz.CourseId).FirstOrDefault();


            ViewBag.QA = quizattempt;
            ViewBag.CID = CID;


            return View();
        }
    }
}

Views/Quizzes/AddQuestions.cshtml
@model ChurchSystem.Models.Question

@{
    ViewBag.Title = "AddQuestions";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Add Questions</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <style>
        .green-border {
            border: 5px solid green;
        }

        .red-border {
            border: 5px solid red;
        }
    </style>


    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" asp-for="QuizId" /> <!-- Ensure this is set properly -->

        <div class="form-group">
            @Html.LabelFor(model => model.Text,"Question", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer,"Option 1", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control red-border" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer2,"Option 2", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer2, new { htmlAttributes = new { @class = "form-control red-border" } })
                @Html.ValidationMessageFor(model => model.Answer2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorrectAnswer,"Correct Answer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorrectAnswer, new { htmlAttributes = new { @class = "form-control green-border" } })
                @Html.ValidationMessageFor(model => model.CorrectAnswer, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add-Question" class="btn btn-primary" />
            </div>
        </div>
    </div>
}





@section scripts{


}

Views/Quizzes/AdminAttemptReview.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}




@{
    var list = ViewBag.QA as List<ChurchSystem.Models.QuizAttempt>;
    var countCorrect = list.Where(a => a.IsCorrect).Count();
    var countTotal = list.Count();
    var percentageScore = (countCorrect / (double)countTotal) * 100;
    var passed = percentageScore >= 50; // Assuming 50% is the passing score
}


<center>
    <h2>Quiz Attempt Review</h2>
    <hr style="width:50%" />
</center>

<div class="card" style="width: 50%; margin: 0 auto; padding: 20px;">
    <div class="card-body text-center">
        <h4 class="card-title">Quiz Score</h4>
        <div class="progress mb-3" style="height: 30px;">
            <div class="progress-bar" role="progressbar" style="width: @percentageScore%;"
                 aria-valuenow="@percentageScore" aria-valuemin="0" aria-valuemax="100">
                @percentageScore.ToString("0.00")%
            </div>
        </div>
        <p class="card-text">@ViewBag.user got @countCorrect out of @countTotal correct</p>
        <h5 class="card-text text-@((passed) ? "success" : "danger")">
            @if (passed)
            {
                <span>Quiz Passed</span>
            }
            else
            {
                <span>Quiz Failed</span>
            }
        </h5>
    </div>
</div>

<br />
<br />
<br />


@foreach (var item in list)
{
    <div>
        @if (item.IsCorrect)
        {
            <center>
                <div class="col-md-10">
                    <div class="card" style="background-color:lawngreen">
                        <div class="card-header">
                            Question : @item.Question.Text <br />
                            Your Answer: @item.SubmittedAnswer
                            <hr />
                            Correct
                        </div>
                    </div>
                </div>
                <br />
                <br />
            </center>
        }

        else
        {
            <div class="col-md-10">
                <div class="card" style="background-color:red">
                    <div class="card-header">
                        Question : @item.Question.Text<br />
                        Your Answer: @item.SubmittedAnswer
                        <hr />
                        Incorrect
                        Correct Answer: @item.CorrectAnswer
                    </div>
                </div>
            </div>
            <br />
            <br />
        }
    </div>

}

<center>
    <a class="btn btn-outline-success" href="@Url.Action("ViewResults","Quizzes", new {id = ViewBag.CID})">
        Done
    </a>
</center>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />  
<br />
<br />
<br />
<br />

@section scripts{



}

Views/Quizzes/AttemptReview.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}




@{
    var list = ViewBag.QA as List<ChurchSystem.Models.QuizAttempt>;
    var countCorrect = list.Where(a => a.IsCorrect).Count();
    var countTotal = list.Count();
    var percentageScore = (countCorrect / (double)countTotal) * 100;
    var passed = percentageScore >= 50; // Assuming 50% is the passing score
}


<center>
    <h2>Your Quiz Attempt Review</h2>
    <hr style="width:50%" />
</center>

<div class="card" style="width: 50%; margin: 0 auto; padding: 20px;">
    <div class="card-body text-center">
        <h4 class="card-title">Quiz Score</h4>
        <div class="progress mb-3" style="height: 30px;">
            <div class="progress-bar" role="progressbar" style="width: @percentageScore%;"
                 aria-valuenow="@percentageScore" aria-valuemin="0" aria-valuemax="100">
                @percentageScore.ToString("0.00")%
            </div>
        </div>
        <p class="card-text">You got @countCorrect out of @countTotal correct!</p>
        <h5 class="card-text text-@((passed) ? "success" : "danger")">
            @if (passed)
            {
                <span>Congratulations, you passed the quiz!</span>
            }
            else
            {
                <span>Sorry, you did not pass the quiz.</span>
            }
        </h5>
    </div>
</div>

<br />
<br />
<br />


@foreach (var item in list)
{
    <div>

        @if (item.IsCorrect)
        {
            <center>
                <div class="col-md-10">
                    <div class="card" style="background-color:lawngreen">
                        <div class="card-header">
                            Question : @item.Question.Text <br />
                            Your Answer: @item.SubmittedAnswer
                            <hr />
                            Correct
                        </div>
                    </div>
                </div>
                <br />
                <br />
            </center>
        }

        else
        {
            <div class="col-md-10">
                <div class="card" style="background-color:red">
                    <div class="card-header">
                        Question : @item.Question.Text<br />
                        Your Answer: @item.SubmittedAnswer
                        <hr />
                        Incorrect
                        Correct Answer: @item.CorrectAnswer
                    </div>
                </div>
            </div>
            <br />
            <br />
        }
    </div>

}
<br />
<br />

<center>
    <div class="button">
        <a href="@Url.Action("BibleStudy", "Courses", new { id = ViewBag.CID})" class="btn">Back To Bible Study</a>
    </div>

</center>
<br />
<br />
<br />
<br />
@section scripts{



}

Views/Quizzes/Create.cshtml
@model ChurchSystem.Models.Quiz

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

@{ 
    var id = ViewBag.CID;
}

<h2>New Bible-Study Quiz</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <center>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Quiz Title ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
    </center>


    @Html.HiddenFor(model => model.CourseId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Next" class="btn btn-primary" />
        </div>
    </div>
</div>
}




@section scripts{

}

Views/Quizzes/Details.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2></h2>


<br/>
<br/>
<center>
    <div class="card border-success mb-3" style="max-width: 20rem;">
        <div class="card-header">Quiz Details</div>
        <div class="card-body">
            <h4 class="card-title">@ViewBag.T</h4>
            <p class="card-text">Total Questions: @ViewBag.QC</p>
            <p class="card-text">Date Created: @ViewBag.Date.ToString("d MMMM yyyy")</p>
            <hr />

            <a href="@Url.Action("Take","Quizzes", new {id = ViewBag.Id})">
            <button type="button"  class="btn btn-success">Start Quiz</button>
            </a>
        </div>
    </div>
</center>




<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />



@section scripts{




}

Views/Quizzes/Finish.cshtml
@model ChurchSystem.Models.Quiz
@{
    ViewBag.Title = "Finish";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

@{
    var quiz = ViewBag.QS as List<ChurchSystem.Models.Question>;
}

<center>
    <h2>Quiz Q &amp; A</h2>
    <br />
</center>

@foreach (var q in quiz)
{
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">@q.Text</h5><br />
            <ul>
                <li> &bull;  @q.Answer </li>
                <li> &bull;  @q.Answer2</li>
                <li> &bull; @q.CorrectAnswer</li>
            </ul>
            <a class=" btn btn-outline-danger" href="@Url.Action("DeleteConfirmed", new {id = q.Id})">Remove</a><br />
        </div>
    </div>

}
<br/>
<br />
<br />
<center>
    <a class=" btn btn-outline-primary" href="@Url.Action("AddQuestions","Quizzes", new { QuizId = ViewBag.ID })">Add Question</a><br/><br />
    <a class=" btn btn-outline-success" href="@Url.Action("quizIndex","Quizzes", new { id = ViewBag.CID, successMessage = "Quiz Created" })">Finish</a>
</center>
<br />
<br />
<br />
<br />


@section scripts{

}

Views/Quizzes/Index.cshtml
@model IEnumerable<ChurchSystem.Models.Quiz>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}


<h2>Quizzes</h2>

<p>
    @Html.ActionLink("Create New Quiz", "Create")
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th></th>
    </tr>

    @foreach (var quiz in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => quiz.Title)</td>
            <td>@Html.ActionLink("Take", "Take", new { id = quiz.QuizID })</td>
            <td>@Html.ActionLink("Finish", "Finish", new { id = quiz.QuizID })</td>
        </tr>
    }

</table>



@section scripts{





}

Views/Quizzes/Review.cshtml
@model ChurchSystem.Models.StudentQuizResult


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

<h2>Quiz Review</h2>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}


<p>Quiz Title: @Model.Quiz.Title</p>
<p>Your Score: @Model.Score</p>

@section scripts{
    
    
    
    
}

Views/Quizzes/Take.cshtml
@model ChurchSystem.Models.Quiz


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/dLayout.cshtml";
}

@{
    var num = 1;
}

<br />
<br />
 


<h2>@Model.Title</h2>

<br />
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    foreach (var question in Model.Questions)
    {
        <div>
            <h4></h4>

        </div>

        <center>
            <div class="col-md-10">
                <div class="card border-success mb-9" style="max-width: 90rem;">
                    <div class="card-header"> Question: @num @{ num++; }</div>
                    <div class="card-body">
                        <h4 class="card-title">@question.Text</h4>
                        @foreach (var answer in question.ShuffledAnswers)
                        {
                            <label>
                                @Html.RadioButton("answers_" + question.Id, answer) @answer
                            </label>
                            <br />
                        }
                    </div>
                </div>
            </div>
        </center>

        <br />
        <br />
        <br />

    }
    <center>
        <input type="submit" value="Submit" class="btn btn-primary" />
    </center>

}
<br />
<br />
<br />
<br />
<br />
<br />


@section scripts{




}

Views/Quizzes/ViewResults.cshtml
@model IEnumerable<ChurchSystem.Models.StudentQuizResult>
@{
    ViewBag.Title = "ViewResults";
    Layout = "~/Views/Shared/dLayout.cshtml";
}


<br />
<br />
<center>
    <h2>Quiz Attempts/Results </h2>
    <hr style="width:50%" />
</center>

<center>
    <table class="table">
        <tr>
            <th>
                User
            </th>
            <th>
                Score
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.user)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Score)
                </td>
                <td>
                    <a class="btn btn-outline-success" href="@Url.Action("AdminAttemptReview","Quizzes",new {id = item.StudentQuizResultId})">
                        View Attempt
                    </a>
                </td>
            </tr>
        }

    </table>
</center>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

@section scripts{



} 

Views/Quizzes/quizIndex.cshtml
@{
    ViewBag.Title = "quizIndex";
    Layout = "~/Views/Shared/dLayout.cshtml";

    var qzs = ViewBag.qz as List<ChurchSystem.Models.Quiz>;

}

<h2>Quizzes</h2>



@if (qzs == null)
{

}
else
{

    foreach (var q in qzs)
    {


        <div class="col-md-12">
            <div class="card">
                <div class="card-header" style="background-color:lightblue">
                    Date: [ @q.CreatedAt.ToString("d MMMM yyyy") ] <br />
                    <hr />
                    <div class="row">
                        <img src="~/Content/img/quiz.png" width="50" height="50" /> <h4 style="padding-top:9px; padding-left:9px">@q.Title</h4>

                        <div class="button" style="padding-inline-start:600px">
                            <a class="btn btn-outline-info" href="@Url.Action("ViewResults","Quizzes", new { id = q.CourseId})">View Attempts</a>
                            <a class=" btn btn-outline-danger" href="@Url.Action("QDeleteConfirmed", new {id = q.QuizID})">Remove</a><br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <br />
    <br />
    <br />

    <div class="col-md-12">
        <div class="card">
            <div class="card-header" style="background-color:lightblue">
                <div class="row">
                    <img src="~/Content/img/quiz.png" width="50" height="50" />

                    <div class="button" style="padding-inline-start:10px; padding-top:10px">
                        <a class="btn btn-outline-info" href="@Url.Action("Create","Quizzes", new {CourseId  = ViewBag.ID})">Create New Quiz</a>
                    </div>
                </div>
                <hr />
            </div>
        </div>
    </div>
}

<br />
<br />
<a class=" btn btn-outline-primary" href="@Url.Action("AdmminIndex","Courses")">Back To Bible Studies</a>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />



@section scripts{
    <!-- Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

    <!-- Toastr JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script>
        // Define the showSuccessMessage function
        function showSuccessMessage(message) {
            toastr.success(message);
        }

        // Handle the Toastr notification.
        $(document).ready(function () {
            // Check if a success message exists in the query string (added after redirection).
            var urlParams = new URLSearchParams(window.location.search);
            if (urlParams.has("successMessage")) {
                var successMessage = urlParams.get("successMessage");
                showSuccessMessage(successMessage);
            }
        });
    </script>
} 

Views/Quizzes/userReport.cshtml
@model IEnumerable<ChurchSystem.Models.StudentQuizResult>

@{
    ViewBag.Title = "userReport";
    Layout = "~/Views/Shared/dLayout.cshtml";
}


<center>
    <h2>Student Report</h2>
    <hr style="width:50%" />
</center>


<h4>Courses Completed </h4>
<hr style="width:50%" />
@if(ViewBag.comp != null)
            {
                <img src="~/Content/img/medalt.gif" width="50" height="50" /> @ViewBag.comp
            }
else
            {
                <p>no Courses Completed Yet</p>
            }
<br />
<br />
<h4>Quiz Attempts/Results </h4>
<hr style="width:50%" />


<center>
    <table class="table">
        <tr>
            <th>
                Quiz
            </th>
            <th>
                Passed
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    Quiz @Html.DisplayFor(modelItem => item.QuizId)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Passed)
                </td>
                <td>
                    <a class="btn btn-outline-success" href="@Url.Action("AdminAttemptReview","Quizzes",new {id = item.StudentQuizResultId})">
                        View Attempt
                    </a>
                </td>
            </tr>
        }

    </table>
</center>


@section scripts{



} 